# Generated by Django 3.0.6 on 2020-05-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True)),
                ('month', models.SmallIntegerField()),
                ('day', models.SmallIntegerField()),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
